easy_admin:
    entities:
        Board:
            class: App\Entity\Board
            label: 'Meeting board'
            form:
                fields:
                    - 'mac'
                    - { property: 'place', type: 'text', label: 'Place' }
                    - { property: 'lastSeen', type: 'datetime', label: 'Last seen on' }
                    - { property: 'sync', type: 'checkbox' , label: 'Sync device?' }
        Calendar:
            class: App\Entity\Calendar
            form:
                fields:
                    - 'id'
                    - { property: 'name', type: 'text', label: 'Name'}
                    - { property: 'Manager', label: 'Calendar type', type: choice, type_options: {choices: {'Google calendar':'GoogleCalendarManager', 'Outlook':'OutlookManager'}}}
                    - board
        Event:
            class: App\Entity\Event
        User:
            class: App\Entity\User